# Generated by Django 5.2 on 2025-04-14 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=50)),
                ('versao', models.CharField(max_length=20)),
                ('funcionalidade_principal', models.TextField(blank=True)),
                ('protocolos_suportados', models.CharField(max_length=100)),
                ('capacidades_dados', models.CharField(max_length=100)),
                ('contato_responsavel', models.CharField(max_length=100)),
                ('requisitos_autenticacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('endpoint', models.TextField()),
                ('formato_dados', models.CharField(max_length=20)),
                ('metodos_permitidos', models.CharField(blank=True, max_length=100)),
                ('autenticacao', models.CharField(blank=True, max_length=50)),
                ('operacoes_suportadas', models.TextField(blank=True)),
                ('exemplo_dados', models.TextField(blank=True)),
                ('esquema', models.TextField(blank=True)),
                ('throttling', models.TextField(blank=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='SPPOI.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='EstiloIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=50)),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('sistema_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integracoes_destino', to='SPPOI.sistema')),
                ('sistema_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integracoes_origem', to='SPPOI.sistema')),
            ],
        ),
    ]
