# Generated by Django 5.2.1 on 2025-06-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPPOI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='session_key',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
