# Generated by Django 4.2 on 2025-04-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPPOI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='session_user_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
